version: "3.8"

services:
  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tornamap
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: .                # usa el Dockerfile del repo
    image: tornamap-backend:latest
    container_name: backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:postgresql://postgres:5432/tornamap
      DB_USERNAME: admin
      DB_PASSWORD: 1234
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./media:/media       # si necesitas persisitir uploads, etc.
    restart: unless-stopped

volumes:
  postgres_data: