#logging:
#  level:
#    org.springframework.security: DEBUG

# server @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
server:
  error:
    include-message: always
    include-stacktrace: never
    include-binding-errors: never
    whitelabel.enabled: true
  servlet:
    session:
      timeout: 15m

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# spring @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
spring:
  profiles:
    active: dev # Perfil por defecto
  application:
    name: TORNAMAP-backend
  thymeleaf:
    check-template-location: false
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: true
  jackson:
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
  session:
    store-type: jdbc
    jdbc.initialize-schema: always
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 10MB  # Tama침o m치ximo de archivo
      max-request-size: 10MB  # Tama침o m치ximo de la solicitud (puede incluir varios archivos)
# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

# ------------------ PERFIL DEV ------------------
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:my_db;COLLATION=ENGLISH STRENGTH PRIMARY
    username: tornamap
    password: tornamap
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
email:
  enabled: false