#logging:
#  level:
#    org.springframework.security: DEBUG

# server @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
server:
  error:
    include-message: always
    include-stacktrace: never
    include-binding-errors: never
    whitelabel.enabled: true
  servlet:
    session:
      timeout: 15m

# @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

spring:
  profiles:
    active: dev # Perfil por defecto
  application:
    name: TORNAMAP-backend
  thymeleaf:
    check-template-location: false
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: true
  jackson:
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
  session:
    store-type: jdbc
    jdbc.initialize-schema: always
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 10MB  # Tamaño máximo de archivo
      max-request-size: 10MB  # Tamaño máximo de la solicitud (puede incluir varios archivos)

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require   # ← “External Database URL” de Render, pero cambiá el prefijo a postgresql
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
email:
  enabled: true

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:my_db;COLLATION=ENGLISH STRENGTH PRIMARY
    username: tornamap
    password: tornamap
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
email:
  enabled: false